services:
  express-app:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "5000:3000"

  fastapi-app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  react-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  angular-app:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
