services:
  express-app:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    container_name: express-container
    image: express-image:latest
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: fastapi-container
    image: fastapi-image:latest
    networks:
      - app-network

  react-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-container
    image: react-image:latest
    networks:
      - app-network

  angular-app:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-container
    image: angular-image:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge