services:
  express-app:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    container_name: express-container

  fastapi-app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      container_name: fastapi-container

  react-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-container

  angular-app:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      container_name: angular-container
